name: 什么值得买自动签到

on:
  schedule:
  # github默认utc时间，北京时间在原来基础上减8
  - cron: 11 3  * * *
  workflow_dispatch:


jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: enwaiax/smzdm_bot
      env:
        ANDROID_COOKIE: ${{ secrets.ANDROID_COOKIE }}
        SK: ${{ secrets.SK }}
        PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
        SC_KEY: ${{ secrets.SC_KEY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        TG_BOT_API: ${{ secrets.TG_BOT_API }}
    steps:
      - name: Working
        run: |
          python /smzdm_bot/main.py
